name: flutter_usgs_earthquakes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
